### ISSUE TITLE
Package are currently outdated.

### ISSUE THREAD

**Issue by saracen24** [conda-forge/conan-feedstock#128]
It looks like bot-automerge fail.

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by AnticliMaxtic** [comment]
I would also like to see this updated, the PyPI version is now at 1.36.0 and conda-forge is sitting at 1.33.1

**Comment by abloemert** [comment]
All versions up to 1.36.0 are now also added to conda-forge, sorry for the delay!
