### ISSUE TITLE
Requirements are out of sync with upstream. 

### ISSUE THREAD

**Issue by ruilvo** [conda-forge/conan-feedstock#158]
The requirements are out of sync with upstream. 

Namely `- jinja2 >=2.9,<3` in [L42](https://github.com/conda-forge/conan-feedstock/blob/master/recipe/meta.yaml#L42), is outdated by [this commit](https://github.com/conan-io/conan/commit/bbdec0a377c8e30bf5ef0ad68ff4745bba43b20d).

**Comment by ruilvo** [comment]
CC @abloemert

**Comment by zabereer** [comment]
Any chance of having this fixed please? I can submit a PR if required.

**Comment by zabereer** [comment]
Thanks @ruilvo  :+1:
