### ISSUE TITLE
When will new conda package be available

### ISSUE THREAD

**Issue by zabereer** [conda-forge/conan-feedstock#160]
I would like to see #158 in conda package for conan.
Confusingly latest conan release https://github.com/conan-io/conan/releases is 1.43.4 (week ago) while conda package contains 1.45.0 (3 weeks ago) - https://anaconda.org/conda-forge/conan
thanks.

**Comment by abloemert** [comment]
v1.43.4 is a patch release of v1.43, in the meantime v1.45 of Conan is also available.

I added v1.43.4 now in a separate branch, see #161
